# Generated by Django 4.2.3 on 2024-02-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('username', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('rent_start_time', models.DateField()),
                ('rent_finish_time', models.DateField()),
                ('price', models.FloatField()),
                ('salary', models.FloatField(verbose_name=0.0)),
                ('favorit', models.BooleanField(default=False)),
                ('location', models.TextField(default='Beni-Seuf')),
                ('discount', models.FloatField(default=0.0)),
                ('level', models.IntegerField(default=0)),
                ('bedrooms', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('area', models.FloatField(default=0.0)),
                ('description', models.CharField(default='null', max_length=50)),
                ('conditions', models.TextField(default='null')),
                ('ava', models.CharField(default='null', max_length=100)),
                ('rev', models.BooleanField(default=False)),
                ('furnished', models.BooleanField(default=False)),
                ('viewer', models.FloatField(default=0.0)),
                ('video', models.FileField(default='null', null=True, upload_to='vedios_house')),
            ],
        ),
    ]
