# Generated by Django 4.2.3 on 2024-02-29 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='salary',
        ),
    ]
