# Generated by Django 4.2.3 on 2024-03-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_offer_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOffermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('rent_start_time', models.DateField()),
                ('rent_finish_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='commentmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('images', models.ImageField(blank=True, null=True, upload_to='imagggeee/')),
                ('date', models.DateField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='requestmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('images', models.ImageField(blank=True, null=True, upload_to='imageee/')),
                ('date', models.DateField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='offer',
            new_name='offermodel',
        ),
    ]
