# Generated by Django 4.2.3 on 2024-03-11 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_offerimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerimages',
            name='offerimg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img', to='app1.offermodel'),
        ),
    ]
